### ISSUE TITLE
PpmDecompress.decompress() freezes when decoding certain BitInputStream

### ISSUE THREAD

**Issue by orolle** [nayuki/Reference-arithmetic-coding#11]
Hi Nayuki,

I use your java PPM algorithm as a similarity measure between text strings to detect similar sentences.

When I compress "Hello World! " with PpmCompress.compress() and decompress the resulting OutputStream with PpmDecompress.decompress() again I get, as expected, "Hello World! ". When I do the same with the String "Hello World! Hello World! " then PpmDecompress.decompress() freezes and 1 core is 100% utilized. Maybe a thread is caught in a loop?

Here is my clojure code to recreate the bug:
```
(let [input "Hello World! Hello World! "
      baos-c (java.io.ByteArrayOutputStream.)
      charset "UTF-8"]
  (io.nayuki.PpmCompress/compress
    (-> input
        (.getBytes charset)
        (java.io.ByteArrayInputStream.))
    baos-c)
  (let [compressed (.toByteArray baos-c)
        _ (println (count compressed))
        intermediate (java.io.ByteArrayInputStream. compressed)
        baos-d (java.io.ByteArrayOutputStream.)]
    (println "before")
    (io.nayuki.PpmDecompress/decompress intermediate baos-d)
    (println "after")
    (String. (.toByteArray baos-d))))
```

**Comment by nayuki** [comment]
The decompressor is indeed caught in a loop. Study the example PpmCompress more closely: It uses a try-with-resources statement, which will call `close()` on the BitOutputStream. **This is not an optional action; it is mandatory!**

This is because `compress()` writes a sequence of bits, which might not be an exact multiple of 8 bits, but `BitOutputStream` writes to an underlying byte stream - so the user needs to tell the bit stream that it has finished and to pad out the remaining bits of the partial byte.

https://github.com/nayuki/Reference-arithmetic-coding/blob/deb456ffc08f44fc1973c7836198222861bc2f87/java/src/PpmCompress.java#L42-L46
