### ISSUE TITLE
Error in arithmetic decoder

### ISSUE THREAD

**Issue by rmrao** [nayuki/Reference-arithmetic-coding#13]
Awesome resource here, thanks for putting this together! I think there's a small error in the decoder - specifically [this line](https://github.com/nayuki/Reference-arithmetic-coding/blob/2b03459323c3b38bfaa2623e7eaae2e3b5f3ea91/python/arithmeticcoding.py#L183) should be `-1` instead of `+1` (which would match the `update` function. Looks like the issue is present in the C++ code as well. I tested the decoding and changing this does fix the "code out of range" error I was getting.

**Comment by nayuki** [comment]
The way you cited the commit by hash and a very specific line of code, is good. However, I don't see any problems with that line of code or the context. The calculation of `range = self.high - self.low + 1` is correct to the best of my knowledge. I don't see how your proposed change would "match the `update` function", because [it uses `+ 1` as well](https://github.com/nayuki/Reference-arithmetic-coding/blob/2b03459323c3b38bfaa2623e7eaae2e3b5f3ea91/python/arithmeticcoding.py#L72).

I don't have your input data, any potential modifications to my library code, your main program, the sequence of commands you ran, or any other details to reproduce the "code out of range" error that you allege.

However, a common user mistake when using my library, especially when writing out a compressed bit stream, is forgetting to explicitly `close()` the BitOutputStream. It is a serious but subtle error to forget this step because the writer buffers bits in an incomplete byte, and only by calling `close()` can you guarantee that the last partial byte is flushed out properly.

**Comment by rmrao** [comment]
Sorry this is my mistake. Was adapting your code for my own project and I made a typo in the update function.
