### ISSUE TITLE
Why flush() in python's arithmeticcoding's ArithmeticEncoder just need to write out 1?

### ISSUE THREAD

**Issue by sonack** [nayuki/Reference-arithmetic-coding#4]
I have read the [original Mark Nelson's blog](https://marknelson.us/posts/2014/10/19/data-compression-with-arithmetic-coding.html), and his implementation is below:

```c++
  pending_bits++;
  if ( low < MODEL::ONE_FOURTH )
    put_bit_plus_pending(0, pending_bits);
  else
    put_bit_plus_pending(1, pending_bits);
```

So, I am a little confused about it, could you kindly give me more explaination? In addition, thanks for your so clear code and sharing spirit!

**Comment by sonack** [comment]
I have understand it, because there are infinite zeros when reading code file is at eof.
and 1000000..... is always in [low, high].
💯

**Comment by nayuki** [comment]
You have answered your own question correctly.

Indeed in my arithmetic coding implementation, the termination logic differs from Mark Nelson's logic. This is because my bit input stream generates an infinite sequence of 0 bits after the data terminates, whereas Mark allows the stream to read arbitrary data (such as data from the next segment of unrelated data, not necessarily encoded with arithmetic coding).

Thanks for citing Mark's quality article - I read through it and it was a good refresher for me on the topic.
